[workspace]
members = ["clazzy", "clazzy_bot"]
resolver = "2"

[workspace.package]
version = "0.1.1"

[workspace.dependencies]
clazzy = { path = "./clazzy", version = "0.1.1" }
clazzy_bot = { path = "./clazzy_bot", version = "0.1.0" }
